//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRFZ_Auto.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRFZ_Auto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 明日方舟-自动脚本 V1.3  on 2022_06_15 肉鸽愧影、普通关卡挂机 的本地化字符串。
        /// </summary>
        internal static string gametitle {
            get {
                return ResourceManager.GetString("gametitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.普通关卡挂机适用于主线关卡，日常轮换龙门币,经验本等关卡以及活动关卡(界面要和主线关卡一致)
        ///当前支持活动:尘影余音(LE1-LE7 关卡)
        ///2.本脚本会循环指定次数或者直到理智用完。
        ///3.本脚本会在强制更新，闪断更新，凌晨4点更新，停服等情况下停止。不会重新回到关卡挂机。 
        ///4.请在关卡准备页面勾选了代理指挥后点击开始
        ///5.请先按照教程里设置模拟器和电脑，和肉鸽的设置是一样的。
        ///6.可以预先手动碎石/吃应急理智液。如有需要，可以用本程序的碎石\吃药，吃药=吃应急理智恢复剂。请确保你有你指定数量的理智液数量和源石数量。
        ///7.可以在高级设置里启用碎石相关选项 的本地化字符串。
        /// </summary>
        internal static string nor_tips {
            get {
                return ResourceManager.GetString("nor_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap qr {
            get {
                object obj = ResourceManager.GetObject("qr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 新版策略选择指南:
        ///1.纯刷钱模式:适合肉鸽已经满级的刷钱用，选突击战术分队,干员(煌&gt;山&gt;帕拉斯),策略只勾选存钱,在商店退出(不进入二层),避开紧急。其余都不选
        ///2.刷等级模式-突击战术分队:干员(煌&gt;山&gt;帕拉斯),策略除了 在商店退出都选,可以选紧急优先
        ///3.刷等级模式-后勤分队(+20源石锭):干员(山&gt;煌&gt;帕拉斯),策略除了 在商店退出都选,建议选避开紧急(因为精一的煌/帕拉斯容易翻车,山的话也有小概率失败)
        ///4.其他:可以自由选择一些选项。在商店退出(不进入二层)请慎重选择，因为进入第二层直接+30分。纯刷钱可以放弃这30分。
        ///5.节点优先级:
        ///避开紧急:将优先选非战斗节点,次选普通作战,如只剩紧急作战那只能选紧急。
        ///不避开紧急:将优先选非战斗节点,次选紧急作战,如只剩普通作战那只能选普通作战。
        ///紧急优先:优先选紧急作战,次选 非战斗节点,最后如果只有普通作战那只能选普通作战。
        ///自定义:你可以自己组合紧急/普通战斗/非战斗节点的选择优先级。
        ///6.可以点击下方查看得分详细说明。 的本地化字符串。
        /// </summary>
        internal static string showTip {
            get {
                return ResourceManager.GetString("showTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者本人@涯S @DR涯 :
        ///0.本程序使用图像识别,adb模拟点击等技术,不篡改游戏数据,不扫描游戏内存,不会让你的帐号获得你原本不能得到的东西。
        ///1.本程序永久免费,不会有付费的版本。
        ///2.禁止任何人将本项目用于商用。
        ///3.本项目不定时更新,项目维护更新是需要人力时间的。
        ///4.本程序放出二维码并不是说需要付费，只是让有意感谢的使用者打赏本人。你的支持将是本项目更新的动力。
        ///5.捐赠所得将用于游戏月卡或维护本项目。
        ///6.本程序仅做软件开发学习交流使用，请在下载24小时后自行删除。 的本地化字符串。
        /// </summary>
        internal static string str_proto {
            get {
                return ResourceManager.GetString("str_proto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ===================================
        ///新版策略选择指南:
        ///1.纯刷钱模式:适合肉鸽已经满级的刷钱用，选突击战术分队,干员(煌&gt;山&gt;帕拉斯),策略只勾选存钱,在商店退出(不进入二层),避开紧急。其余都不选
        ///2.刷等级模式-突击战术分队:干员(煌&gt;山&gt;帕拉斯),策略除了 在商店退出都选,可以选紧急优先
        ///3.刷等级模式-后勤分队(+20源石锭):干员(山&gt;煌&gt;帕拉斯),策略除了 在商店退出都选,建议选避开紧急(因为精一的煌/帕拉斯容易翻车,山的话也有小概率失败)
        ///4.其他:可以自由选择一些选项。在商店退出(不进入二层)请慎重选择，因为进入第二层直接+30分。纯刷钱可以放弃这30分。
        ///5.节点优先级:
        ///避开紧急:将优先选非战斗节点,次选普通作战,如只剩紧急作战那只能选紧急。
        ///不避开紧急:将优先选非战斗节点,次选紧急作战,如只剩普通作战那只能选普通作战。
        ///紧急优先:优先选紧急作战,次选 非战斗节点,最后如果只有普通作战那只能选普通作战。
        ///自定义:你可以自己组合紧急/普通战斗/非战斗节点的选择优先级。
        ///6.可以点击下方查看得分详细说明。
        ///7.请尽可能点满 幕后筹备 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tips {
            get {
                return ResourceManager.GetString("tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap TIPS_png {
            get {
                object obj = ResourceManager.GetObject("TIPS_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 更新计划:
        ///1.不定时维护本项目,修复bug
        ///2.放弃打通肉鸽第二层的计划
        ///3.保全派驻-多伦矿场-4核心自动通关 的本地化字符串。
        /// </summary>
        internal static string update_pro {
            get {
                return ResourceManager.GetString("update_pro", resourceCulture);
            }
        }
    }
}
